server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: test
    password: 4rfv$RFV
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    cache: false # ???? ?????????false ??????
    suffix: .html # ????? ???ftl
    charset: UTF-8 # ????
    template-loader-path: classpath:/templates/